services:
  db:
    image: mysql:latest
    volumes:
      - 1_criacao_compose_db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./config/db.env
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "800:80"
    env_file:
      - ./config/wp.env

volumes:
  1_criacao_compose_db_data:
    external: true