version: latest

services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  
  api:
    depends_on:
      - mongo-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
